title: rj
description: >-
  A Ruby command-line JSON processor

permalink: /:categories/:year/:month/:day/:title/

markdown: kramdown

nav:
  Home: '/'
  Get it: '/download'
  Tutorial: '/tutorial'
  Code: 'https://github.com/nilsding/rj'
  Bugs: 'https://github.com/nilsding/rj/issues'
  Changelog: '/changelog'
