---

name: Build

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed

    steps:
      - name: Install dependencies
        run: |
          zypper ar -f https://download.opensuse.org/repositories/devel:/languages:/crystal/openSUSE_Tumbleweed/devel:languages:crystal.repo
          zypper --gpg-auto-import-keys in -y crystal ruby git gcc

      - uses: actions/checkout@v3

      - name: Build project
        run: rake build

      - name: Run tests
        run: ruby test/rj_test.rb

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Install dependencies
        run: |
          brew install crystal ruby git

      - uses: actions/checkout@v3

      - name: Build project
        run: rake build

      - name: Run tests
        run: ruby test/rj_test.rb
